// DO NOT EDIT! This file is automatically generated when compiling the icon font via the `fontcustom compile`
// command. To make changes, please edit the "fonts/templates/icons.ts" template file and regenerate.
export type Icons =<% @glyphs.each do |name, value| %>
  | `<%= name.to_s %>`<% end %>;
